version: "3.9"
services:
  server:
    build: .
    depends_on:
      - mongo
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
    deploy:
      restart_policy:
        condition: on-failure
    command: bash -c "/usr/wait-for-it.sh --timeout=0 mongo:27017 && node src/index.js"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
